from __future__ import annotations

from functools import lru_cache

from .schemas import KnifeCompatibilityEdge, KnifeConstraintSet, KnifePrimitive


BASELINE_KNIFE_IDS: tuple[str, ...] = (
    "self_image_feeding",
    "high_ground_pity",
    "fake_vulnerability",
    "delayed_asking",
    "relationship_withdrawal",
    "old_wound_trigger",
    "memory_reframing",
    "courteous_humiliation",
    "gentle_absorption",
    "baited_concession",
)


def _knife(
    *,
    knife_id: str,
    name: str,
    intent: str,
    mechanism: str,
    emotional_disguise: tuple[str, ...],
    target_vulnerabilities: tuple[str, ...],
    best_arenas: tuple[str, ...],
    risks: tuple[str, ...],
    failure_modes: tuple[str, ...],
    compatible_with: tuple[str, ...],
    incompatible_with: tuple[str, ...],
    scene_restrictions: tuple[str, ...] = (),
    target_restrictions: tuple[str, ...] = (),
    observer_requirements: tuple[str, ...] = (),
    anti_conditions: tuple[str, ...] = (),
    backfire_conditions: tuple[str, ...] = (),
    ineffective_conditions: tuple[str, ...] = (),
    flavor_conflicts: tuple[str, ...] = (),
) -> KnifePrimitive:
    return KnifePrimitive(
        id=knife_id,
        name=name,
        intent=intent,
        mechanism=mechanism,
        emotional_disguise=emotional_disguise,
        target_vulnerabilities=target_vulnerabilities,
        best_arenas=best_arenas,
        risks=risks,
        failure_modes=failure_modes,
        compatible_with=compatible_with,
        incompatible_with=incompatible_with,
        constraints=KnifeConstraintSet(
            scene_restrictions=scene_restrictions,
            target_restrictions=target_restrictions,
            observer_requirements=observer_requirements,
            anti_conditions=anti_conditions,
            backfire_conditions=backfire_conditions,
            ineffective_conditions=ineffective_conditions,
            flavor_conflicts=flavor_conflicts,
        ),
    )


@lru_cache(maxsize=1)
def build_default_knife_library() -> tuple[KnifePrimitive, ...]:
    # Tokens are intentionally structured as kind:value so constraint helpers can stay data-driven.
    return (
        _knife(
            knife_id="self_image_feeding",
            name="自我形象喂养",
            intent="借目标自我形象把行动引回反派预设轨道",
            mechanism="先替目标定义何为体面，再让目标为了维护自我形象替反派完成表演",
            emotional_disguise=("理解", "体面", "替你着想"),
            target_vulnerabilities=("identity_anchor", "witness_sensitivity_high"),
            best_arenas=("chaotang", "shijia", "mingsheng"),
            risks=("public_backfire", "status_bet"),
            failure_modes=("目标不在乎体面评价", "上位者改写现场叙事"),
            compatible_with=("baited_concession",),
            incompatible_with=("relationship_withdrawal",),
            scene_restrictions=("stake:reputation",),
            target_restrictions=("identity_anchor:required",),
            observer_requirements=("observer_role:judge",),
            anti_conditions=("witness_sensitivity:low",),
            backfire_conditions=("observer_alignment:target", "power_edge:target_over_villain"),
            ineffective_conditions=("identity_anchor:diffuse",),
            flavor_conflicts=("control_preference:private_invasion",),
        ),
        _knife(
            knife_id="high_ground_pity",
            name="高位怜悯",
            intent="通过怜悯姿态把目标压进低位叙事",
            mechanism="以看似宽容的姿态替目标解释失败，从而把目标钉死在被恩准的位置",
            emotional_disguise=("慈悲", "宽恕", "抬举"),
            target_vulnerabilities=("pride", "witness_sensitivity_high"),
            best_arenas=("chaotang", "menpai", "mingsheng"),
            risks=("hypocrisy_exposure", "public_backfire"),
            failure_modes=("目标愿意当众翻脸", "旁观者更同情目标"),
            compatible_with=("self_image_feeding",),
            incompatible_with=(),
            scene_restrictions=("visibility:public", "stake:reputation"),
            observer_requirements=("observer_role:witness",),
            anti_conditions=("resistance_style:direct_confrontation",),
            backfire_conditions=("observer_alignment:target", "power_edge:target_over_villain"),
            ineffective_conditions=("witness_sensitivity:low",),
            flavor_conflicts=("cruelty_visibility:hidden",),
        ),
        _knife(
            knife_id="fake_vulnerability",
            name="伪造脆弱",
            intent="让目标主动放下警惕并伸手救援",
            mechanism="展示可控的脆弱表象，触发目标的保护欲或愧疚补偿",
            emotional_disguise=("无助", "真诚", "被伤害"),
            target_vulnerabilities=("protector_complex", "guilt_prone"),
            best_arenas=("qingzhai", "shitu"),
            risks=("trust_collapse",),
            failure_modes=("表演过量显得廉价", "目标只想解决问题不想安慰人"),
            compatible_with=("gentle_absorption", "delayed_asking"),
            incompatible_with=("courteous_humiliation",),
            target_restrictions=("weak_point:protector_complex",),
            anti_conditions=("defense_style:skeptical",),
            backfire_conditions=("visibility:public",),
            ineffective_conditions=("resistance_style:task_only",),
            flavor_conflicts=("cruelty_visibility:open",),
        ),
        _knife(
            knife_id="delayed_asking",
            name="延迟索取",
            intent="先给安全感，再在未来节点回收代价",
            mechanism="把索取延迟到目标心理负债更高时再提，从而提高顺从概率",
            emotional_disguise=("体贴", "不着急", "你先休息"),
            target_vulnerabilities=("guilt_prone", "debt_sensitive"),
            best_arenas=("shitu", "qingzhai", "ziyuan"),
            risks=("window_missed",),
            failure_modes=("时机拖过头", "目标提前识别负债结构"),
            compatible_with=("fake_vulnerability", "baited_concession", "gentle_absorption"),
            incompatible_with=(),
            target_restrictions=("weak_point:debt_sensitive",),
            anti_conditions=("time_pressure:high",),
            backfire_conditions=("observer_role:judge",),
            ineffective_conditions=("time_horizon:short",),
        ),
        _knife(
            knife_id="relationship_withdrawal",
            name="关系抽离",
            intent="通过撤回情感供给迫使目标失衡追索",
            mechanism="突然收回原有的回应和陪伴，让目标在失去中暴露需求结构",
            emotional_disguise=("疲惫", "失望", "沉默"),
            target_vulnerabilities=("attachment_hunger", "abandonment_fear"),
            best_arenas=("qingzhai", "shitu"),
            risks=("bond_break",),
            failure_modes=("目标直接断联", "场面过于公开导致反派丢控制"),
            compatible_with=("old_wound_trigger",),
            incompatible_with=("gentle_absorption", "self_image_feeding"),
            scene_restrictions=("visibility:private",),
            target_restrictions=("core_need:connection",),
            anti_conditions=("stake:survival",),
            backfire_conditions=("observer_role:recovery_node",),
            ineffective_conditions=("resistance_style:detached",),
        ),
        _knife(
            knife_id="old_wound_trigger",
            name="旧伤触发",
            intent="借目标旧伤把当前判断拉进熟悉的痛点回路",
            mechanism="在安全阈值边缘触碰旧伤，使目标把当下误判成过去创伤的重演",
            emotional_disguise=("无意", "熟悉", "只是提起旧事"),
            target_vulnerabilities=("old_wound", "identity_fragility"),
            best_arenas=("shitu", "qingzhai", "shijia"),
            risks=("trauma_backlash",),
            failure_modes=("触发过猛导致彻底防御", "旁观者立即介入修复"),
            compatible_with=("memory_reframing",),
            incompatible_with=(),
            target_restrictions=("weak_point:old_wound",),
            anti_conditions=("defense_style:detached",),
            backfire_conditions=("observer_role:buffer",),
            ineffective_conditions=("wound_activation:already_saturated",),
        ),
        _knife(
            knife_id="memory_reframing",
            name="记忆改写",
            intent="重新解释过去一幕，从而改写目标对现在的判断",
            mechanism="把既有记忆重新包装成另一种因果含义，让目标主动调整责任归属",
            emotional_disguise=("澄清", "回忆", "其实当时并不是那样"),
            target_vulnerabilities=("identity_anchor", "meaning_hunger"),
            best_arenas=("shitu", "qingzhai", "menpai"),
            risks=("counter_evidence",),
            failure_modes=("目标记忆很稳", "第三方证据戳穿改写"),
            compatible_with=("old_wound_trigger", "baited_concession"),
            incompatible_with=(),
            target_restrictions=("identity_anchor:required",),
            anti_conditions=("time_pressure:high",),
            backfire_conditions=("observer_role:transmitter",),
            ineffective_conditions=("resistance_style:evidence_locked",),
        ),
        _knife(
            knife_id="courteous_humiliation",
            name="礼貌羞辱",
            intent="在不失礼的外壳下公开降低目标位格",
            mechanism="用规训式礼貌替目标安排失态位置，让羞耻在众目睽睽下自发完成",
            emotional_disguise=("礼数", "提点", "替你遮丑"),
            target_vulnerabilities=("pride", "witness_sensitivity_high"),
            best_arenas=("chaotang", "menpai", "mingsheng"),
            risks=("high_exposure", "public_backfire"),
            failure_modes=("尺度过重引发群体反感", "目标反咬其借礼杀人"),
            compatible_with=("self_image_feeding",),
            incompatible_with=("fake_vulnerability",),
            scene_restrictions=("visibility:public", "stake:reputation"),
            observer_requirements=("observer_role:judge", "observer_role:witness"),
            anti_conditions=("witness_sensitivity:low",),
            backfire_conditions=("observer_alignment:target", "power_edge:target_over_villain"),
            ineffective_conditions=("identity_anchor:diffuse",),
            flavor_conflicts=("witness_dependence:private",),
        ),
        _knife(
            knife_id="gentle_absorption",
            name="温柔收编",
            intent="以接纳和保护的姿态把目标吸纳进自己的依赖轨道",
            mechanism="通过温和回应与容纳，把目标的自我修复需求绑定到反派身上",
            emotional_disguise=("接纳", "理解", "我来替你承受"),
            target_vulnerabilities=("belonging_hunger", "protector_fatigue"),
            best_arenas=("qingzhai", "shitu"),
            risks=("dependency_overload",),
            failure_modes=("目标把温柔看成控制", "外部危机逼迫目标抽离"),
            compatible_with=("fake_vulnerability", "delayed_asking"),
            incompatible_with=("relationship_withdrawal",),
            target_restrictions=("core_need:belonging",),
            anti_conditions=("stake:survival",),
            backfire_conditions=("observer_role:judge",),
            ineffective_conditions=("resistance_style:autonomy_guarded",),
            flavor_conflicts=("cruelty_visibility:open",),
        ),
        _knife(
            knife_id="baited_concession",
            name="诱饵让步",
            intent="先给出看似退让的空间，再把目标带进更深的承诺结构",
            mechanism="释放有限让步作为诱饵，诱导目标以为自己赢得主动后继续签下更重的账",
            emotional_disguise=("退让", "体面收束", "我已经做出让步"),
            target_vulnerabilities=("win_hunger", "resource_anxiety"),
            best_arenas=("chaotang", "ziyuan", "mingsheng"),
            risks=("concession_locked_in",),
            failure_modes=("让步被当真", "目标宁可不吃诱饵"),
            compatible_with=("self_image_feeding", "delayed_asking", "memory_reframing"),
            incompatible_with=(),
            scene_restrictions=("stake:resource",),
            target_restrictions=("social_priority:status",),
            anti_conditions=("resistance_style:refuse_bargain",),
            backfire_conditions=("power_edge:target_over_villain",),
            ineffective_conditions=("core_need:certainty",),
        ),
    )


@lru_cache(maxsize=1)
def build_compatibility_graph() -> tuple[KnifeCompatibilityEdge, ...]:
    return (
        KnifeCompatibilityEdge(
            left="fake_vulnerability",
            right="delayed_asking",
            relation="compatible",
            reason="先建立救援冲动，再把索取延迟到心理负债升高时回收",
        ),
        KnifeCompatibilityEdge(
            left="old_wound_trigger",
            right="memory_reframing",
            relation="compatible",
            reason="先触发熟悉痛点，再重写其因果解释",
        ),
        KnifeCompatibilityEdge(
            left="self_image_feeding",
            right="baited_concession",
            relation="conditional",
            reason="只有在目标仍想维护体面赢家叙事时才可叠加",
        ),
        KnifeCompatibilityEdge(
            left="fake_vulnerability",
            right="courteous_humiliation",
            relation="incompatible",
            reason="脆弱伪装与公开规训会互相戳穿前后逻辑",
        ),
        KnifeCompatibilityEdge(
            left="relationship_withdrawal",
            right="gentle_absorption",
            relation="incompatible",
            reason="一个撤回供给、一个加深接纳，会把依赖信号彻底打散",
        ),
    )


def get_knife_by_id(
    knife_id: str, *, library: tuple[KnifePrimitive, ...] | None = None
) -> KnifePrimitive:
    for knife in library or build_default_knife_library():
        if knife.id == knife_id:
            return knife
    raise KeyError(f"unknown knife id: {knife_id}")
