from __future__ import annotations

from dataclasses import asdict, dataclass, field
from pathlib import Path

from .evaluation_service import NarrativeV2EvaluationService
from .rule_service import NarrativeV2RuleService
from .schemas import NarrativeV2PreviewRequest
from .search_service import NarrativeV2SearchService
from .state_builder import NarrativeV2StateBuilder
from .validation_service import NarrativeV2ValidationService


@dataclass
class NarrativeV2PreviewService:
    state_builder: NarrativeV2StateBuilder = field(default_factory=NarrativeV2StateBuilder)
    rule_service: NarrativeV2RuleService = field(default_factory=NarrativeV2RuleService)
    search_service: NarrativeV2SearchService = field(default_factory=NarrativeV2SearchService)
    evaluation_service: NarrativeV2EvaluationService = field(default_factory=NarrativeV2EvaluationService)
    validation_service: NarrativeV2ValidationService = field(default_factory=NarrativeV2ValidationService)
    ledger_path: Path | None = None

    def build_preview(self, payload: NarrativeV2PreviewRequest) -> dict[str, object]:
        state = self.state_builder.build(payload.state.model_dump())
        rule_checks = self.rule_service.evaluate(state)
        recommendations = self.search_service.search(state, rule_checks)
        recommendations = self.evaluation_service.rank(recommendations)
        top_action = recommendations[0].action.action if recommendations else ""
        validation = self.validation_service.record(
            case_id=payload.case_id,
            accepted_actions=[check.action for check in rule_checks if check.status == "legal"],
            blocked_actions=[check.action for check in rule_checks if check.status != "legal"],
            top_action=top_action,
            notes="v2 preview generated by rule->search->evaluation pipeline",
        )
        self.validation_service.append_ledger(
            record=validation,
            source="preview",
            path=self.ledger_path,
        )
        evaluation_summary = {
            "count": len(recommendations),
            "top_action": top_action,
            "top_score": recommendations[0].score if recommendations else 0.0,
        }
        return {
            "case_id": payload.case_id,
            "state": asdict(state),
            "rule_checks": [asdict(check) for check in rule_checks],
            "recommendations": [asdict(result) for result in recommendations],
            "evaluation_summary": evaluation_summary,
            "validation": asdict(validation),
        }
