from __future__ import annotations

from dataclasses import asdict, dataclass, field
from pathlib import Path

from alpha_autopilot_v2.domain import SearchResult

from .decision_contract import build_preview_decision
from .evaluation_service import NarrativeV2EvaluationService
from .rule_service import NarrativeV2RuleService
from .schemas import NarrativeV2PreviewRequest
from .search_service import NarrativeV2SearchService
from .state_builder import NarrativeV2StateBuilder
from .validation_service import NarrativeV2ValidationService


@dataclass
class NarrativeV2PreviewService:
    state_builder: NarrativeV2StateBuilder = field(default_factory=NarrativeV2StateBuilder)
    rule_service: NarrativeV2RuleService = field(default_factory=NarrativeV2RuleService)
    search_service: NarrativeV2SearchService = field(default_factory=NarrativeV2SearchService)
    evaluation_service: NarrativeV2EvaluationService = field(default_factory=NarrativeV2EvaluationService)
    validation_service: NarrativeV2ValidationService = field(default_factory=NarrativeV2ValidationService)
    ledger_path: Path | None = None

    def build_preview(self, payload: NarrativeV2PreviewRequest) -> dict[str, object]:
        state = self.state_builder.build(payload.state.model_dump())
        rule_checks = self.rule_service.evaluate(state)
        recommendations = self.search_service.search(state, rule_checks)
        recommendations = self.evaluation_service.rank(recommendations, state=state)
        top_action = recommendations[0].action.action if recommendations else ""
        selected_recommendation = _select_recommendation(top_action, recommendations)
        validation = self.validation_service.record(
            case_id=payload.case_id,
            accepted_actions=[check.action for check in rule_checks if check.status == "legal"],
            blocked_actions=[check.action for check in rule_checks if check.status == "blocked"],
            top_action=top_action,
            notes="v2 preview generated by rule->search->evaluation pipeline",
        )
        ledger_warning: str | None = None
        try:
            self.validation_service.append_ledger(
                record=validation,
                source="preview",
                path=self.ledger_path,
            )
        except Exception as exc:
            # Ledger persistence is best-effort for preview requests.
            ledger_warning = f"{exc.__class__.__name__}: {exc}"
        retention_driver = self.evaluation_service.build_retention_driver(
            selected_recommendation,
            state,
        )
        decision = build_preview_decision(
            rule_checks=rule_checks,
            recommendations=recommendations,
            validation=validation,
            retention_driver=retention_driver,
        )
        evaluation_summary = {
            "count": len(recommendations),
            "top_action": decision["selected_action"],
            "top_score": decision["selected_score"],
        }
        response: dict[str, object] = {
            "case_id": payload.case_id,
            "state": asdict(state),
            "rule_checks": [asdict(check) for check in rule_checks],
            "recommendations": [asdict(result) for result in recommendations],
            "decision": decision,
            "evaluation_summary": evaluation_summary,
            "validation": asdict(validation),
        }
        if ledger_warning:
            response["ledger_warning"] = ledger_warning
        return response


def _select_recommendation(
    selected_action: str,
    recommendations: list[SearchResult],
) -> SearchResult | None:
    for recommendation in recommendations:
        if recommendation.action.action == selected_action:
            return recommendation
    return recommendations[0] if recommendations else None
